version: '3.8'

services:
  omeka-checker:
    build: .
    volumes:
      - ./logs:/app/logs
    environment:
      - TZ=UTC
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID}
    restart: unless-stopped 